#!/usr/bin/env python
# coding: utf-8

# # PCA Task 2 - OLCI Payload Analysis
# 
# This notebook loads Sentinel-3 OLCI payload variables, cleans and aligns the time series, applies PCA, and then uses the PCA outputs to inspect loadings, scores, outliers, clusters, frequency content, and STL decomposition.
# 
# The notebook is organized so that each section first defines helper functions and then runs a short execution cell with the parameters selected for the analysis.
# 

# ## 1. Libraries
# 
# Imports are grouped by purpose: data handling, PCA/scaling, signal processing, seasonal decomposition, and plotting.
# 

# In[1]:


# Data Processing
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings("ignore")

# PCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from scipy.signal import detrend as scipy_detrend

# FFT
from scipy.fft import fft, fftfreq
from scipy.signal import find_peaks
from statsmodels.tsa.seasonal import STL
from scipy.signal import detrend, windows
from scipy.fft import rfft, rfftfreq

# Plotting
import matplotlib.pyplot as plt


# ## 2. Parameters
# 
# Set the mission, payload, and output folder used throughout the notebook. Generated figures are saved under `out_path`.
# 

# In[2]:


mission = "S3A"
payload = "olci"

# Directory where the CSV are located
input_path = ''

# Directory where figures generated by the notebook are saved.
out_path = "./figures/Task2/"
output_dir = os.path.dirname(out_path)
os.makedirs(output_dir, exist_ok=True)


# ## 3. Data Pre-processing
# 
# This section turns the raw product CSV files into clean, time-indexed numerical tables. The same cleaning logic is reused for product variables and text calibration curves.
# 

# ### 3.1 Helper Functions
# 
# `data_fixing` standardizes column names, removes incomplete orbits using the row-count distribution, drops non-informative columns and missing rows, sets the datetime index, and slices the requested period.
# 
# `product_data_opening` loads temperature, energy, and voltage tables and merges them on the common time index.
# 
# `text_calcurve_preprocessing` prepares the text calibration curves so they can later be aligned with the PCA scores.
# 
# `detrend_dataframe` applies detrending to the whole dataframe

# In[3]:


def column_renaming(df):
    df = df.reset_index()
    old_cols = list(df.columns)

    real_cols = [c for c in old_cols if not c.startswith("level_")]

    time_col = real_cols[0]

    rowcount_col = real_cols[1]

    var_cols = real_cols[2:]

    new_cols = []

    var_idx = 0

    for i, col in enumerate(old_cols):

        if i == 0:
            new_cols.append(time_col)

        elif i == 1:
            new_cols.append(rowcount_col)

        elif i % 2 == 0:
            new_cols.append(var_cols[var_idx])
            var_idx += 1

        else:
            new_cols.append(f"Unnamed: {i}")

    df.columns = new_cols
    return df


"""Clean one raw product table and select the requested time interval."""
def data_fixing(ds, start, end):

    # Fixing the name of the columns
    ds = column_renaming(ds)

    # Drop Orbits not completed
    ds    = ds.rename(columns={'Rowcount S3_TM_HKP2':'Rowcount', 'Rowcount S3_TM_HKP1':'Rowcount'})
    mean  = ds["Rowcount"].mean()
    std   = ds["Rowcount"].std()
    lower = mean - std
    upper = mean + std
    ds_orbits = ds[(ds["Rowcount"] >= lower) & (ds["Rowcount"] <= upper)]

    # Keep variables only
    ds_parameters = ds_orbits.loc[:, ~ds_orbits.columns.str.contains("Unnamed:")].drop(columns=["Rowcount"])

    # Drop NaNs before the PCA
    ds_parameters_nonan = ds_parameters.dropna()

    # Set time
    ds_parameters_nonan["Time (ISO8601)"] = pd.to_datetime(ds_parameters_nonan["Time (ISO8601)"])
    ds_fixed = ds_parameters_nonan.rename(columns={'Time (ISO8601)':'time'}).set_index('time')

    # Slice by time interval - available period varies according to the Mission
    ds_slice = ds_fixed.loc[f"{start}-01-01":f"{end}-12-31"]
    return ds_slice

"""Load and merge all numeric product tables used for Task 2."""

def product_data_opening(payload, mission, start, end,input_path=input_path):

    data1 = pd.read_csv(f'{input_path}temperature_{payload}_{mission}.csv')
    data2 = pd.read_csv(f'{input_path}temperature_{payload}_{mission}_1.csv')
    data3 = pd.read_csv(f'{input_path}energy_{payload}_{mission}.csv')
    data4 = pd.read_csv(f'{input_path}voltage_{payload}_{mission}.csv')

    data1_fixed = data_fixing(data1,start,end)
    data2_fixed = data_fixing(data2,start,end)
    data3_fixed = data_fixing(data3,start,end)
    data4_fixed = data_fixing(data4,start,end)

    df_final = pd.concat([data1_fixed, data2_fixed, data3_fixed, data4_fixed], axis=1, join="inner")

    df_final_tokeep = df_final.loc[:, df_final.nunique() > 1]
    df = df_final_tokeep.copy()
    if "time" in df.columns:
        df["time"] = pd.to_datetime(df["time"], errors="coerce")
        df = df.set_index("time")
    df = df.loc[:,~df.columns.duplicated()].copy()
    return df

def text_calcurve_preprocessing(mission, input_path=input_path):
    text_calcurve  = pd.read_csv(f'{input_path}textcalcurve_olci_{mission}.csv')
    text_calcurve1 = pd.read_csv(f'{input_path}textcalcurve_olci_{mission}.csv')
    text_calcurve_fixed  = data_fixing(text_calcurve,2017,2025)
    text_calcurve1_fixed = data_fixing(text_calcurve1,2017,2025)
    textcalcurve_fixed = pd.concat([text_calcurve_fixed, 
                                    text_calcurve1_fixed, 
                                   ], axis=1,
                                   join="inner")
    textcalcurve_tokeep = textcalcurve_fixed.loc[:, textcalcurve_fixed.nunique() > 1]
    textcalcurves = textcalcurve_tokeep.copy()
    if "time" in textcalcurves.columns:
        textcalcurves["time"] = pd.to_datetime(textcalcurves["time"], errors="coerce")
        textcalcurves = textcalcurves.set_index("time")
    textcalcurves = textcalcurves.loc[:,~textcalcurves.columns.duplicated()].copy()
    return textcalcurves

def detrend_dataframe(df):
    """
    Removal of the linear trend to all the numeric columns
    """
    df_out = df.copy()
    numeric_cols = df_out.select_dtypes(include=[np.number]).columns
    df_out[numeric_cols] = df_out[numeric_cols].apply(
        lambda x: detrend(x.values),
        axis=0,
        result_type='expand'
    )

    return df_out


# ### 3.2 Load Data
# 
# The main dataframe `df` contains the numerical product variables used as PCA input. `textcalcurves` is kept separate and aligned only when needed for the calibration-curve outlier plots.
# 

# In[4]:


detrend_df = True


# In[5]:


# Main product variables.
df = product_data_opening(payload, mission, 2017, 2024)

if detrend_df == True:
    # Applying PCA to the detrended variables
    df = detrend_dataframe(df)

# Text calibration curves aligned later with PCA scores.
textcalcurves = text_calcurve_preprocessing(mission)


# ## 4. Principal Component Analysis
# 
# The PCA is run on numerical columns only. Variables are standardized before decomposition so that the PCs describe relative variability rather than raw-unit magnitude.
# 

# ### 4.1 PCA Function
# 
# The function returns:
# 
# - `explained`: variance explained by each principal component;
# - `loadings`: contribution of each original variable to each PC;
# - `scores`: time series of the projected observations in PCA space.
# 

# In[6]:


def pca_execution(df, n_components, mission_name):
    X_df = df.select_dtypes(include=[np.number])
    X_df = X_df.dropna(axis=0, how="any")
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_df.values)

    pca = PCA(n_components=n_components, random_state=0)
    X_pca = pca.fit_transform(X_scaled)
    explained = pca.explained_variance_ratio_

    print(f"OLCI | Mission {mission_name} - Variances explained per component:", explained)
    print(f"OLCI | Mission {mission_name} - Cumulated variances:",               np.cumsum(explained))

    loadings = pd.DataFrame(
        pca.components_.T,
        index=X_df.columns,
        columns=[f"PC{i+1}" for i in range(n_components)])

    scores = pd.DataFrame(
        X_pca,
        index=X_df.index,
        columns=[f"PC{i+1}" for i in range(n_components)])
    return explained, loadings, scores


# ### 4.2 Execute PCA
# 
# Choose the number of components and run the decomposition on the cleaned dataset.
# 

# In[7]:


explained, loadings, scores = pca_execution(
    df,            # Input dataset.
    10,            # Number of PCA components.
    "Sentinel 3A"  # Mission name used in printed messages.
)


# ## 5. PCA Results
# 
# Select one principal component and inspect its score time series, variable loadings, and related groups of variables.
# 

# ### 5.1 Select Component
# 
# Change `pca` to analyze a different principal component in the following sections.
# 

# In[8]:


# Select the principal component used in the following analyses.
pca = 1


# In[9]:


# Quick check of the cleaned dataset structure.
df.head()


# ### 5.2 Loadings
# 
# Loadings show which variables contribute positively or negatively to the selected PC. The horizontal threshold lines are used later to define correlated and anti-correlated clusters.
# 

# In[10]:


def plot_pca_loadings(loadings, pc="PC1", out_path=out_path):
    """Plot variable loadings for one selected principal component."""
    series = loadings[pc]

    plt.figure(figsize=(22,10))

    plt.bar(
        series.index,
        series.values,
        color="steelblue",
        edgecolor="black",
        linewidth=0.5
    )

    # Zero line
    plt.axhline(0, color="black", linewidth=1)

    # Threshold lines
    plt.axhline(
        0.15,
        color="maroon",
        linestyle="--",
        linewidth=1.7
    )

    plt.axhline(
        -0.15,
        color="maroon",
        linestyle="--",
        linewidth=1.7
    )

    # Fixed y-axis range
    plt.ylim(-0.3, 0.3)

    plt.xlabel("Variables", fontsize=25)
    plt.ylabel("Loading value", fontsize=25)
    #plt.title(f"PCA Loadings - {pc}", fontsize=25)

    plt.xticks(rotation=45, ha="right", size=18)
    plt.yticks(size=20)

    plt.grid(axis="y", alpha=0.3)

    plt.tight_layout()

    plt.savefig(f'{out_path}loadings_{pc.lower()}.png')

    plt.show()


# In[ ]:


plot_pca_loadings(loadings, f"PC{pca}", out_path=out_path)


# ### 5.3 Scores
# 
# Scores show how strongly each timestamp projects onto the selected PC. The plot includes both the full period and a zoom on one selected year.
# 

# In[11]:


def plot_pc_timeseries(
    ts,
    title="PC1 score",
    out_path=out_path,
    detrend=False,
    zoom_year=2022
):
    """Plot a PCA score over the full period and a selected year."""
    if detrend:
        d = "_detrended"
        ts_det = scipy_detrend(ts.values)
        ts = pd.Series(ts_det, index=ts.index)

    else:
        d = ""

    ts = ts.copy()
    ts.index = pd.to_datetime(ts.index)

    ts_zoom = ts[ts.index.year == zoom_year]

    fig, axes = plt.subplots(
        2, 1,
        figsize=(12, 9),
        sharex=False
    )

    # Full time series
    axes[0].plot(
        ts.index.to_numpy(),
        ts.to_numpy(),
        linewidth=0.8,
        color="steelblue"
    )

    axes[0].set_yscale("symlog", linthresh=10)
    axes[0].axhline(0, color="black", linewidth=0.8)
    axes[0].set_xlabel("Time", fontsize=18)
    axes[0].set_ylabel("Score", fontsize=18)
    #axes[0].set_title(f"{title}{d}", fontsize=25)
    axes[0].tick_params(axis="both", labelsize=13)
    axes[0].grid(alpha=0.3)

    # Zoomed time series
    axes[1].plot(
        ts_zoom.index.to_numpy(),
        ts_zoom.to_numpy(),
        linewidth=0.8,
        color="steelblue"
    )

    axes[1].set_yscale("symlog", linthresh=10)
    axes[1].axhline(0, color="black", linewidth=0.8)
    axes[1].set_xlabel("Time", fontsize=20)
    axes[1].set_ylabel("Score", fontsize=20)
    axes[1].set_title(f"Zoom: {zoom_year}", fontsize=22)
    axes[1].tick_params(axis="both", labelsize=16)
    axes[1].grid(alpha=0.3)

    plt.tight_layout()

    plt.savefig(f"{out_path}scores_pc{pca}{d}_zoom_{zoom_year}.png")

    plt.show()


# In[45]:


plot_pc_timeseries(
    scores[f"PC{pca}"],
    title=f"PC{pca} score",
    detrend=False,
    zoom_year=2024
)


# ## 6. Outlier Detection
# 
# Rare events are detected on the detrended PCA score using a standard-deviation threshold. The threshold is intentionally configurable because different PCs can have different score distributions.
# 

# ### 6.1 Helper Function

# In[12]:


def outliers_sigma(df, col, k):
    """Detect rare events after detrending a selected score column."""
    ts = df[col].values
    ts_detrended = scipy_detrend(ts)
    ts_detrended = pd.Series(ts_detrended, index=df.index)

    mean = ts_detrended.mean()
    std = ts_detrended.std()

    lower = mean - k * std
    upper = mean + k * std

    df_out = ts_detrended[(ts_detrended < lower) | (ts_detrended > upper)]

    return df_out


# In[ ]:


plot_pc_timeseries(
    scores[f"PC{pca}"],
    title=f"PC{pca} score",
    detrend=False,
    zoom_year=2024
)


# ### 6.2 Detect Rare Events
# 
# The detrended dataframe is prepared for optional plotting. The outlier list is computed from the selected PC score.
# 

# In[14]:


#df_detrended = detrend_dataframe(df)


# In[15]:


if pca == 1:
    std_th = 1.6  # Standard-deviation threshold for rare events.
else:
    std_th = 2.5  # More conservative threshold for the other PCs.

outliers = outliers_sigma(scores, f"PC{pca}", std_th)


# In[16]:


# Time steps classified as rare events.
outliers


# ## 7. Variable Clusters
# 
# Variables are grouped according to their loading sign and magnitude for the selected PC. Positive loadings form the correlated group, while negative loadings form the anti-correlated group.
# 

# In[17]:


corr_factor = 0.15  # Minimum absolute loading used to assign variables to a cluster.

variable_pca_anticorr = loadings[loadings[f"PC{pca}"] < -corr_factor][f"PC{pca}"].to_dict()
print(f"PCA{pca} - anticorrelated parameters:", variable_pca_anticorr.keys())

variable_pca_corr = loadings[loadings[f"PC{pca}"] > corr_factor][f"PC{pca}"].to_dict()
print(f"PCA{pca} - correlated parameters:", variable_pca_corr.keys())


# ## 8. Outliers on Product Variables
# 
# This section projects the PCA outlier timestamps back onto one selected product variable, making it easier to inspect whether the PC rare events correspond to visible behavior in the original signal.
# 

# ### 8.1 Plotting Function
# 

# In[18]:


def outlier_detection_and_plot(
    df,
    col,
    outliers,
    year,
    out_path=out_path,
    detrend=False
):
    """Plot one variable and highlight the PCA outlier timestamps."""
    if detrend:
        d = "_detrended"
    else:
        d = ""

    ts = df[col].copy()
    ts.index = pd.to_datetime(ts.index)

    outlier_index = pd.to_datetime(outliers.index)
    outlier_index = outlier_index.intersection(ts.index)

    ts_out = ts.loc[outlier_index]

    # Selected year
    ts_year = ts.loc[f"{year}-01-01":f"{year}-12-31"]

    out_year_idx = outlier_index.intersection(ts_year.index)
    ts_out_year = ts_year.loc[out_year_idx]

    fig, axes = plt.subplots(
        2, 1,
        figsize=(14, 9),
        sharex=False
    )

    # Full time series
    axes[0].plot(
        ts.index.to_numpy(),
        ts.to_numpy(),
        linewidth=0.8,
        color="steelblue",
        label="Time series"
    )

    if not ts_out.empty:
        axes[0].scatter(
            ts_out.index.to_numpy(),
            ts_out.to_numpy(),
            color="red",
            s=30,
            label="Outliers",
            zorder=3
        )

    axes[0].set_title(
        f"{col} - full time series{d}",
        fontsize=25
    )
    axes[0].set_xlabel("Time", fontsize=20)
    axes[0].set_ylabel("Value", fontsize=20)
    axes[0].tick_params(axis="both", labelsize=16)
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Zoom on selected year
    axes[1].plot(
        ts_year.index.to_numpy(),
        ts_year.to_numpy(),
        linewidth=0.8,
        color="steelblue",
        label="Time series"
    )

    if not ts_out_year.empty:
        axes[1].scatter(
            ts_out_year.index.to_numpy(),
            ts_out_year.to_numpy(),
            color="red",
            s=30,
            label="Outliers",
            zorder=3
        )

    axes[1].set_title(
        f"{col} - {year}{d}",
        fontsize=25
    )
    axes[1].set_xlabel("Time", fontsize=20)
    axes[1].set_ylabel("Value", fontsize=20)
    axes[1].tick_params(axis="both", labelsize=16)
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()

    plt.savefig(
        f"{out_path}outliers_{col}_pc{pca}_full_and_{year}{d}.png"
    )

    plt.show()


# ### 8.2 Plot Selected Variable
# 
# Choose `col` from one of the correlated or anti-correlated clusters. Set `plot_detrended_var=True` to plot the detrended version prepared earlier.
# 

# In[ ]:


# Select a variable from one PCA cluster and visualize it at the detected outlier timestamps.
col = "CCB0241K_AVG"

outlier_detection_and_plot(
    df=df,
    col=col,
    outliers=outliers,
    year=2024,
    detrend=detrend_df
)


# ## 9. Outliers on Text Calibration Curves
# 
# Text calibration curves are aligned with PCA scores on the common timestamps, then inspected using the same outlier markers.
# 

# ### 9.1 Alignment Function
# 

# In[19]:


def aligning_text_and_scores(textcalcurves, scores):
    """Align text calibration curves with PCA score timestamps."""
    common_index = scores.index.intersection(textcalcurves.index)

    scores_aligned = scores.loc[common_index].sort_index()
    state_aligned  = textcalcurves.loc[common_index].sort_index()
    pca_with_state = scores_aligned.join(state_aligned, how="inner").dropna(axis=0, how="any")
    return pca_with_state


# ### 9.2 Plot Selected Calibration Curve
# 

# In[20]:


pca_with_state = aligning_text_and_scores(textcalcurves, scores)


# In[ ]:


calcurve = "CCB0102X_AVG"

try:
    outlier_detection_and_plot(
        df=pca_with_state,
        col=calcurve,
        outliers=outliers,
        year=2024,
        detrend=False
    )
except Exception as exc:
    print(f"No variables in this cluster, or selected cal-curve not available: {exc}")


# ### 9.3 Stricter Rare-event Threshold
# 
# If the first threshold is too permissive for this calibration-curve view, recompute the outliers with a higher sigma threshold and repeat the plot.
# 

# In[56]:


# Stricter threshold used when the first threshold marks too many events.
outliers_updated = outliers_sigma(scores, f"PC{pca}", 4)


# In[ ]:


try:
    outlier_detection_and_plot(
        df=pca_with_state,
        col=calcurve,
        outliers=outliers_updated,
        year=2024,
        detrend=False
    )
except Exception as exc:
    print(f"No variables in this cluster, or selected cal-curve not available: {exc}")


# ## 10. Frequency Analysis
# 
# The FFT section checks the dominant periods in either one selected PC score or a weighted combination of the first three PCs.
# 

# ### 10.1 Helper Functions
# 

# In[21]:


def ts_creation(ts, detrend=False):
    """Prepare a regular time series and return its sampling interval in seconds."""
    ts.index = pd.to_datetime(ts.index)
    ts = ts.sort_index()
    dt = (ts.index[1] - ts.index[0]).total_seconds()
    if detrend == True:
        ts_detrended = scipy_detrend(ts)
        ts = pd.Series(ts_detrended, index=ts.index)
        dt = (ts.index[1] - ts.index[0]).total_seconds()
    return ts, dt

def plot_power_spectrum(ts, dt, combo, detrend,
                        remove_annual=False,
                        out_path=out_path):
    """Compute and plot the power spectrum of a PCA score or score combination."""

    color = 'steelblue'

    if detrend == True:
        d = 'detrended'
    else:
        d = ''

    signal = ts.values
    N = len(signal)

    if remove_annual == True:
        signal = signal - np.mean(signal)
        window = windows.hann(len(signal))
        signal = signal * window
        N = len(signal)

        yf = rfft(signal)
        xf = rfftfreq(N, d=dt)
        ra = 'removed_annual'

    else:
        yf = fft(signal - np.mean(signal))
        xf = fftfreq(N, dt)
        ra = ''


    power = np.abs(yf)**2

    # masking positive frequencies
    mask = xf > 0
    freq = xf[mask]
    power = power[mask]

    # conversion: freq -> period
    period_days = 1 / freq / 86400
    order = np.argsort(period_days)
    period_days = period_days[order]
    power = power[order]

    # Peaks
    peaks, _ = find_peaks(power, prominence=np.max(power)*0.05)

    # Overwrite the parameters if remove_annual is set True
    if remove_annual == True:
        mask = (period_days > 0.1) & (period_days < 100)
        period_days = period_days[mask]
        power = power[mask]
        peaks, properties = find_peaks(power, prominence=np.max(power)*0.05)

        n_peaks = 3
        idx = np.argsort(power[peaks])[-n_peaks:]
        peaks = peaks[idx]



    # plot
    plt.figure(figsize=(10,5))

    plt.plot(period_days, power, linewidth=1,color=color)

    plt.scatter(period_days[peaks], power[peaks], color="red", zorder=3)

    for p in peaks:

        period = period_days[p]

        if period < 1:
            label = f"{period*24:.1f} h"
        else:
            label = f"{period:.1f} d"

        plt.annotate(
            label,
            (period_days[p], power[p]),
            textcoords="offset points",
            xytext=(5,5),
            fontsize=12
        )

    plt.xscale("log")
    plt.yscale("log")
    plt.tick_params(axis="both", labelsize=16)
    plt.xlabel("Period [days]",fontsize=20)
    plt.ylabel("Power",fontsize=20)

    #if combo == True:

    #    plt.title(f"Combination of first three PCAs' Power Spectrum {d} {ra}")

    #else:

    #    plt.title(f"PCA{pca}s' Power Spectrum {d} {ra}")

    plt.grid(True, which="both", alpha=0.3)
    plt.tight_layout()
    if combo == True:
        plt.savefig(f'{out_path}fft_{d}_{ra}_power_spectrum_combo.png')
    else:
        plt.savefig(f'{out_path}fft_{d}_{ra}_power_spectrum_pca{pca}.png')
    return power, peaks, period_days


# ### 10.2 Select Time Series
# 

# In[22]:


combo = False

if combo:
    # Weighted combination of the first three PCs using their explained variance.
    ts = (
        scores["PC1"].dropna() * explained[0]
        + scores["PC2"].dropna() * explained[1]
        + scores["PC3"].dropna() * explained[2]
    ).copy()
else:
    ts = scores[f"PC{pca}"].dropna()

detrend = False
ts_fixed, dt = ts_creation(ts, detrend)


# ### 10.3 Power Spectrum
# 

# In[23]:


power, peaks, period_days = plot_power_spectrum(ts_fixed, dt, combo, detrend)


# ### 10.4 Remove Annual and Semi-annual Cycles
# 
# This helper removes annual and semi-annual harmonic components through a least-squares fit, then the spectrum is recomputed on the adjusted signal.
# 

# In[24]:


def remove_annual_semiannual_cycles(ts):
    """
    Removes annual and semi-annual harmonic components from a time series.
    Assumes ts has a datetime index.
    """

    ts = ts.copy()
    ts.index = pd.to_datetime(ts.index)

    mask = ts.notna()
    y = ts.loc[mask].to_numpy()

    # Time in days from start
    t = (ts.loc[mask].index - ts.loc[mask].index[0]).total_seconds() / 86400

    annual_period = 365.25
    semiannual_period = 365.25 / 2

    X = np.column_stack([
        np.ones(len(t)),
        np.sin(2 * np.pi * t / annual_period),
        np.cos(2 * np.pi * t / annual_period),
        np.sin(2 * np.pi * t / semiannual_period),
        np.cos(2 * np.pi * t / semiannual_period),
    ])

    beta, _, _, _ = np.linalg.lstsq(X, y, rcond=None)

    fitted_cycle = X @ beta

    ts_removed = ts.copy()
    ts_removed.loc[mask] = y - fitted_cycle

    return ts_removed


# In[25]:


power, peaks, period_days = plot_power_spectrum(
    ts_fixed,
    dt,
    combo,
    detrend,
    remove_annual=True
)


# ## 11. STL Decomposition
# 
# STL separates the selected signal into trend, daily seasonality, and residuals. The clipping step only stabilizes the decomposition and plotting against extreme values.
# 

# ### 11.1 STL Function
# 

# In[30]:


def plt_STL(
    ts,
    combo,
    detrend,
    remove_annual=False,
    component="residuals",
    out_path=out_path
):
    """Run STL and plot one selected decomposition component."""
    color = "steelblue"

    if detrend:
        d = "detrended"
    else:
        d = ""

    if remove_annual:
        ts = remove_annual_semiannual_cycles(ts)
        ra = "removed_annual_semiannual"
    else:
        ra = ""

    # Remove extremes only for plotting/decomposition stability
    q01, q99 = ts.quantile([0.01, 0.99])
    ts_clean = ts.clip(lower=q01, upper=q99)

    # STL decomposition
    period = 288   # 5 minutes -> 288 samples/day
    stl = STL(ts_clean, period=period, robust=True)
    res = stl.fit()

    component = component.lower()

    if component in ["trend", "low_frequency"]:
        y = res.trend
        component_label = "Trend / low-frequency component"

    elif component in ["seasonality", "seasonal", "daily_seasonality"]:
        y = res.seasonal
        component_label = "Daily seasonality"

    elif component in ["residuals", "residual", "resid"]:
        y = res.resid
        component_label = "Residuals"

    else:
        raise ValueError(
            "component must be one of: 'trend', 'seasonality', or 'residuals'"
        )

    plt.figure(figsize=(14, 5))

    plt.plot(
        y.index.to_numpy(),
        y.to_numpy(),
        linewidth=1,
        color=color
    )

    plt.axhline(0, color="black", linewidth=0.8)

    plt.title(component_label, fontsize=25)
    plt.xlabel("Time", fontsize=20)
    plt.ylabel("Value", fontsize=20)
    plt.xticks(size=18)
    plt.yticks(size=18)
    plt.grid(True, alpha=0.3)

    if combo:
        filename = f"{out_path}fft_{d}_{ra}_STL_combo_{component}.png"
    else:
        filename = f"{out_path}fft_{d}_{ra}_STL_pca{pca}_{component}.png"

    plt.tight_layout()
    plt.savefig(filename)

    plt.show()
    return res


# ### 11.2 Plot Decomposition Components
# 

# In[ ]:


plt_STL(ts, combo=combo, detrend=detrend, component="residuals")


# In[ ]:


plt_STL(ts, combo=combo, detrend=detrend, component="seasonality")


# In[ ]:


plt_STL(ts, combo=combo, detrend=detrend, component="trend")

