#!/usr/bin/env python
# coding: utf-8

# Converted from: Telemetry_Task3_Multi_mission_analysis (1).ipynb

# %% [markdown] cell 1
# # Telemetry Task 3 - Multi-mission OLCI Analysis
#
# This notebook compares the same OLCI temperature telemetry payload across Sentinel-3A and Sentinel-3B. The workflow loads and cleans the two mission datasets, runs PCA separately for each mission, then compares loadings, scores, outliers, frequency content, and STL decomposition components.
#
# The structure mirrors the single-mission PCA notebook, but each analysis step is duplicated or plotted side by side for the two missions.

# %% [markdown] cell 2
# ## 1. Libraries
#
# Imports are grouped by purpose: data handling, PCA/scaling, signal processing, seasonal decomposition, and plotting.

# %% [code] cell 3
# Data Processing
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings("ignore")

# PCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from scipy.signal import detrend as scipy_detrend

# FFT
from scipy.fft import fft, fftfreq
from scipy.signal import find_peaks
from statsmodels.tsa.seasonal import STL
from scipy.signal import detrend, windows
from scipy.fft import rfft, rfftfreq

# Plotting
import matplotlib.pyplot as plt

# %% [markdown] cell 4
# ## 2. Parameters
#
# Set the payload, shared comparison period, and output folder. The start year is chosen so that both Sentinel-3A and Sentinel-3B have available data.

# %% [code] cell 5
"""
Task 3: same payload, different missions.
The analysis compares OLCI temperature telemetry from Sentinel-3A and Sentinel-3B.
"""
payload = "olci"

# Sentinel-3B launched in 2018; start from 2019 to compare both missions.
start = 2019
end = 2025

input_path = "" # Fill in with the data path

# Directory where figures generated by the notebook are saved.
out_path = "./figures/Task3/"
output_dir = os.path.dirname(out_path)
os.makedirs(output_dir, exist_ok=True)

# %% [markdown] cell 6
# ## 3. Data Pre-processing
#
# This section prepares the temperature telemetry for each mission. The functions standardize the raw tables, remove incomplete orbits, keep useful sensor variables, set the time index, and retain only the requested date range.

# %% [markdown] cell 7
# ### 3.1 Helper Functions
#
# `product_data_opening` loads the two temperature files for one mission and returns a cleaned mission dataframe.
#
# `text_calcurve_preprocessing` prepares text calibration curves separately so they can later be aligned with PCA score timestamps.
#
# `detrend_dataframe` applies detrending to the whole dataframe

# %% [code] cell 8
def column_renaming(df):
    df = df.reset_index()
    old_cols = list(df.columns)
    
    real_cols = [c for c in old_cols if not c.startswith("level_")]
    
    time_col = real_cols[0]
    
    rowcount_col = real_cols[1]
    
    var_cols = real_cols[2:]
    
    new_cols = []
    
    var_idx = 0
    
    for i, col in enumerate(old_cols):
    
        if i == 0:
            new_cols.append(time_col)
    
        elif i == 1:
            new_cols.append(rowcount_col)
    
        elif i % 2 == 0:
            new_cols.append(var_cols[var_idx])
            var_idx += 1
    
        else:
            new_cols.append(f"Unnamed: {i}")
    
    df.columns = new_cols
    return df
    
"""Clean one raw telemetry table and select the requested time interval."""

def data_fixing(ds, start, end):
    # Fixing the name of the columns
    ds = column_renaming(ds)
    
    # Drop Orbits not completed
    ds    = ds.rename(columns={'Rowcount S3_TM_HKP2':'Rowcount', 'Rowcount S3_TM_HKP1':'Rowcount'})
    mean  = ds["Rowcount"].mean()
    std   = ds["Rowcount"].std()
    lower = mean - std
    upper = mean + std
    ds_orbits = ds[(ds["Rowcount"] >= lower) & (ds["Rowcount"] <= upper)]
    
    # Keep variables only
    ds_parameters = ds_orbits.loc[:, ~ds_orbits.columns.str.contains("Unnamed:")].drop(columns=["Rowcount"])
    
    # Drop NaNs before the PCA
    ds_parameters_nonan = ds_parameters.dropna()
    
    # Set time
    ds_parameters_nonan["Time (ISO8601)"] = pd.to_datetime(ds_parameters_nonan["Time (ISO8601)"])
    ds_fixed = ds_parameters_nonan.rename(columns={'Time (ISO8601)':'time'}).set_index('time')

    # Slice by time interval - available period varies according to the Mission
    ds_slice = ds_fixed.loc[f"{start}-01-01":f"{end}-12-31"]
    return ds_slice

"""Load and merge the temperature files for one selected mission."""

def product_data_opening(payload, mission, start, end, input_path=input_path):
    
    # Opening the data in your folder
    data0 = pd.read_csv(f'{input_path}temperature_{payload}_{mission}.csv')
    data1 = pd.read_csv(f'{input_path}temperature_{payload}_{mission}_1.csv')

    # Apply preprocessing on the single file
    data0_fixed = data_fixing(data0, start, end)
    data1_fixed = data_fixing(data1, start, end)

    # Merge the multiple files in a single one
    df_merged = pd.concat([data0_fixed, 
                           data1_fixed,
                          ], axis=1)
    df_final = pd.concat([df_merged, data0_fixed], axis=1, join="inner")

    # Exclude columns with a constant value for each time step
    df_final_tokeep = df_final.loc[:, df_final.nunique() > 1]
    
    # Check on time coordinate
    df = df_final_tokeep.copy()
    if "time" in df.columns:
        df["time"] = pd.to_datetime(df["time"], errors="coerce")
        df = df.set_index("time")
        
    # Check on duplicated columns
    df = df.loc[:,~df.columns.duplicated()].copy()
    
    # Check on available sensors
    if len(df.columns == 40):
        print('Temperature sensors for OLCI should be 40: ok')
    else:
        print('Check number of sensors')
    return df


def text_calcurve_preprocessing(mission, input_path=input_path):
    text_calcurve  = pd.read_csv(f'{input_path}textcalcurve_olci_{mission}.csv')
    text_calcurve1 = pd.read_csv(f'{input_path}textcalcurve_olci_{mission}_1.csv')
    text_calcurve_fixed  = data_fixing(text_calcurve,2018,2025)
    text_calcurve1_fixed = data_fixing(text_calcurve1,2018,2025)
    textcalcurve_fixed = pd.concat([text_calcurve_fixed, 
                                    text_calcurve1_fixed, 
                                   ], axis=1,
                                   join="inner")
    textcalcurve_tokeep = textcalcurve_fixed.loc[:, textcalcurve_fixed.nunique() > 1]
    textcalcurves = textcalcurve_tokeep.copy()
    if "time" in textcalcurves.columns:
        textcalcurves["time"] = pd.to_datetime(textcalcurves["time"], errors="coerce")
        textcalcurves = textcalcurves.set_index("time")
    textcalcurves = textcalcurves.loc[:,~textcalcurves.columns.duplicated()].copy()
    return textcalcurves

def detrend_dataframe(df):
    """
    Removal of the linear trend to all the numeric columns
    """
    df_out = df.copy()
    numeric_cols = df_out.select_dtypes(include=[np.number]).columns
    df_out[numeric_cols] = df_out[numeric_cols].apply(
        lambda x: detrend(x.values),
        axis=0,
        result_type='expand'
    )

    return df_out

# %% [markdown] cell 9
# ### 3.2 Load Mission Data
#
# `df_mission1` is Sentinel-3A and `df_mission2` is Sentinel-3B. Both are processed with the same cleaning function to keep the comparison consistent.

# %% [code] cell 10
df_mission1 = product_data_opening(
    payload,
    "S3A",  # Mission identifier used in the filenames.
    start,
    end
)

df_mission2 = product_data_opening(
    payload,
    "S3B",  # Mission identifier used in the filenames.
    start,
    end
)

# %% [code] cell 11
detrend_df = True

# %% [code] cell 12
if detrend_df == True:
    # Applying PCA to the detrended variables
    df_mission1 = detrend_dataframe(df_mission1)
    df_mission2 = detrend_dataframe(df_mission2)

# %% [markdown] cell 13
# ### 3.3 Load Text Calibration Curves
#
# These data are not used as PCA input. They are kept for the later outlier inspection on calibration-curve variables.

# %% [code] cell 14
textcalcurves_m1 = text_calcurve_preprocessing("S3A", in_path=None)
textcalcurves_m2 = text_calcurve_preprocessing("S3B", in_path=None)

# %% [markdown] cell 15
# ## 4. Principal Component Analysis
#
# PCA is run independently for each mission after standardizing numerical variables. This keeps each mission's components based on its own telemetry distribution.

# %% [markdown] cell 16
# ### 4.1 PCA Function
#
# The function returns explained variance, loadings, and score time series for the selected mission dataset.

# %% [code] cell 17
def pca_execution(df, n_components, mission_name):
    X_df = df.select_dtypes(include=[np.number])
    X_df = X_df.dropna(axis=0, how="any")
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_df.values)
    
    pca = PCA(n_components=n_components, random_state=0)
    X_pca = pca.fit_transform(X_scaled)
    explained = pca.explained_variance_ratio_
    
    print(f"OLCI | Mission {mission_name} - Variances explained per component:", explained)
    print(f"OLCI | Mission {mission_name} - Cumulated variances:",               np.cumsum(explained))

    loadings = pd.DataFrame(
        pca.components_.T,
        index=X_df.columns,
        columns=[f"PC{i+1}" for i in range(n_components)])
    
    scores = pd.DataFrame(
        X_pca,
        index=X_df.index,
        columns=[f"PC{i+1}" for i in range(n_components)])
    return explained, loadings, scores

# %% [markdown] cell 18
# ### 4.2 Execute PCA for Both Missions

# %% [code] cell 19
explained_m1, loadings_m1, scores_m1 = pca_execution(
    df_mission1,   # Input dataset.
    10,            # Number of PCA components.
    "Sentinel 3A"  # Mission name used in printed messages.
)

# %% [code] cell 20
explained_m2, loadings_m2, scores_m2 = pca_execution(
    df_mission2,   # Input dataset.
    10,            # Number of PCA components.
    "Sentinel 3B"  # Mission name used in printed messages.
)

# %% [markdown] cell 21
# ## 5. PCA Results
#
# Select the principal component to compare across missions and inspect its loadings and score time series.

# %% [markdown] cell 22
# ### 5.1 Select Component

# %% [code] cell 23
# Select the principal component used in the following comparison.
pca = 1

# %% [markdown] cell 24
# ### 5.2 Loadings Comparison
#
# The two bar plots show how the same PC is built from the telemetry variables in each mission. The threshold lines are later used to define correlated and anti-correlated variable groups.

# %% [code] cell 25
def plot_pca_loadings_double(loadings1, loadings2, mission_name1, mission_name2, out_path=out_path, pc=f"PC{pca}", detrend=False):
    """Compare the loadings of the same PC for two missions."""
    series1 = loadings1[pc]
    series2 = loadings2[pc]

    fig, axes = plt.subplots(2, 1, figsize=(15, 12), sharex=True)

    # 1st mission
    axes[0].bar(
        series1.index,
        series1.values,
        color="steelblue",
        edgecolor="black",
        linewidth=0.5
    )
    axes[0].axhline(0, color="black", linewidth=1)
    axes[0].set_ylabel("Loading value", fontsize=20)
    axes[0].set_title(f"{mission_name1}", fontsize=25)
    axes[0].grid(axis="y", alpha=0.3)
    axes[0].tick_params(axis='y', labelsize=18)
    
    # 2nd mission
    axes[1].bar(
        series2.index,
        series2.values,
        color="darkorange",
        edgecolor="black",
        linewidth=0.5
    )
    axes[1].axhline(0, color="black", linewidth=1)
    axes[1].set_ylabel("Loading value", fontsize=20)
    axes[1].set_title(f"{mission_name2}", fontsize=25)
    axes[1].grid(axis="y", alpha=0.3)
    axes[1].tick_params(axis='y', labelsize=18)
    axes[1].set_ylim(-0.3,0.3)
    axes[0].set_ylim(-0.3,0.3)

    #Threshold lines
    axes[0].axhline(0.15,color='maroon',linewidth=1.7, linestyle="--",)
    axes[0].axhline(-0.15,color='maroon',linewidth=1.7, linestyle="--",)
    axes[1].axhline(0.15,color='maroon',linewidth=1.7, linestyle="--",)
    axes[1].axhline(-0.15,color='maroon',linewidth=1.7, linestyle="--",)
    # Shared x-axis
    plt.xticks(rotation=45, ha="right", size=18)
    axes[1].set_xlabel("Variables", fontsize=20)

    # Saving
    plt.tight_layout()
    #plt.savefig(f'./figures/Task3/loadings_{pc}_comparison.png')
    plt.savefig(f'{out_path}loadings_{pc}_comparison.png')

    plt.show()

# %% [code] cell 26
plot_pca_loadings_double(loadings_m1, loadings_m2, 
                         'Sentinel-3A', 'Sentinel-3B',
                         pc=f"PC{pca}")

# %% [markdown] cell 27
# ### 5.3 Score Comparison
#
# Scores describe how strongly each timestamp projects onto the selected PC. The function plots the full time range plus a yearly zoom for both missions.

# %% [code] cell 28
def plot_pc_timeseries_double(
    ts1,
    ts2,
    mission_name1,
    mission_name2,
    year,
    out_path=out_path,
    pc=f"PC{pca}",
    detrend=False
):
    """Plot full and yearly PCA score time series for two missions."""

    def preprocess(ts):
        values = ts.to_numpy()

        if detrend:
            mask = np.isfinite(values)
            detrended = np.full_like(values, np.nan, dtype=float)

            if mask.sum() > 1:
                detrended[mask] = scipy_detrend(values[mask], type="linear")

            return detrended

        return values

    ts1 = ts1.copy()
    ts2 = ts2.copy()

    ts1.index = pd.to_datetime(ts1.index)
    ts2.index = pd.to_datetime(ts2.index)

    ts1_zoom = ts1[ts1.index.year == year]
    ts2_zoom = ts2[ts2.index.year == year]

    y1 = preprocess(ts1)
    y2 = preprocess(ts2)
    y1_zoom = preprocess(ts1_zoom)
    y2_zoom = preprocess(ts2_zoom)

    fig, axes = plt.subplots(
        2, 2,
        figsize=(18, 10),
        sharex=False
    )

    title_suffix = " (detrended)" if detrend else ""

    # Full time series mission 1
    axes[0, 0].plot(
        ts1.index.to_numpy(),
        y1,
        linewidth=0.8,
        color="steelblue"
    )
    axes[0, 0].set_title(
        f"{mission_name1}{title_suffix}",
        fontsize=25
    )

    # Full time series mission 2
    axes[0, 1].plot(
        ts2.index.to_numpy(),
        y2,
        linewidth=0.8,
        color="darkorange"
    )
    axes[0, 1].set_title(
        f"{mission_name2}{title_suffix}",
        fontsize=25
    )

    # Zoom mission 1
    axes[1, 0].plot(
        ts1_zoom.index.to_numpy(),
        y1_zoom,
        linewidth=0.8,
        color="steelblue"
    )
    axes[1, 0].set_title(
        f"{mission_name1} zoom {year}{title_suffix}",
        fontsize=25
    )

    # Zoom mission 2
    axes[1, 1].plot(
        ts2_zoom.index.to_numpy(),
        y2_zoom,
        linewidth=0.8,
        color="darkorange"
    )
    axes[1, 1].set_title(
        f"{mission_name2} zoom {year}{title_suffix}",
        fontsize=25
    )

    for ax in axes.ravel():
        ax.set_yscale("symlog", linthresh=10)
        ax.axhline(0, color="black", linewidth=1)
        ax.set_ylabel("Score", fontsize=20)
        ax.tick_params(axis="both", labelsize=18)
        ax.grid(alpha=0.3)

    axes[1, 0].set_xlabel("Time", fontsize=20)
    axes[1, 1].set_xlabel("Time", fontsize=20)

    plt.tight_layout()

    d = "_detrended" if detrend else ""

    plt.savefig(
        f"{out_path}scores_{pc}_comparison_full_and_{year}{d}.png"
    )

    plt.show()

# %% [code] cell 29
plot_pc_timeseries_double(
    scores_m1[f"PC{pca}"],
    scores_m2[f"PC{pca}"],
    mission_name1="Sentinel-3A",
    mission_name2="Sentinel-3B",
    year=2024,
    pc=f"PC{pca}",
    detrend=False
)

# %% [markdown] cell 30
# ## 6. Outlier Detection
#
# Rare events are detected on detrended PCA scores using a standard-deviation threshold. This helps focus on unusual short-term behavior rather than long-term drift.

# %% [code] cell 31
def outliers_sigma(df, col, k):
    """Detect rare events after detrending a selected PCA score."""
    ts = df[col].values
    ts_detrended = scipy_detrend(ts)
    ts_detrended = pd.Series(ts_detrended, index=df.index)
    
    mean = ts_detrended.mean()
    std = ts_detrended.std()
    
    lower = mean - k * std
    upper = mean + k * std

    df_out = ts_detrended[(ts_detrended < lower) | (ts_detrended > upper)]
    
    return df_out

# %% [markdown] cell 32
# ### 6.1 Detect Outliers for Both Missions

# %% [code] cell 33
outliers_m1 = outliers_sigma(scores_m1, f"PC{pca}", 4)
outliers_m2 = outliers_sigma(scores_m2, f"PC{pca}", 4)

print(f"Sentinel-3A has {len(outliers_m1)} outliers in the period {start}-{end}")
print(f"Sentinel-3B has {len(outliers_m2)} outliers in the period {start}-{end}")

# %% [code] cell 34
# Time steps classified as rare events for Sentinel-3A.
outliers_m1

# %% [markdown] cell 35
# ## 7. Variable Clusters
#
# Variables are grouped by loading sign and magnitude. Positive loadings are considered correlated with the selected PC; negative loadings are anti-correlated.

# %% [code] cell 36
corr_factor = 0.15  # Minimum absolute loading used to assign variables to a cluster.

variable_pca_anticorr_m1 = loadings_m1[loadings_m1[f"PC{pca}"] < -corr_factor][f"PC{pca}"].to_dict()
variable_pca_anticorr_m2 = loadings_m2[loadings_m2[f"PC{pca}"] < -corr_factor][f"PC{pca}"].to_dict()

variable_pca_corr_m1 = loadings_m1[loadings_m1[f"PC{pca}"] > corr_factor][f"PC{pca}"].to_dict()
variable_pca_corr_m2 = loadings_m2[loadings_m2[f"PC{pca}"] > corr_factor][f"PC{pca}"].to_dict()

print(f"PCA{pca} - Sentinel-3A, anti-correlated parameters:", variable_pca_anticorr_m1.keys())
print(f"PCA{pca} - Sentinel-3A, correlated parameters:", variable_pca_corr_m1.keys())

print(f"PCA{pca} - Sentinel-3B, anti-correlated parameters:", variable_pca_anticorr_m2.keys())
print(f"PCA{pca} - Sentinel-3B, correlated parameters:", variable_pca_corr_m2.keys())

# %% [markdown] cell 37
# ## 8. Outliers on Product Variables
#
# This section maps PCA outlier timestamps back to an original telemetry variable that belongs to a shared cluster across both missions.

# %% [markdown] cell 38
# ### 8.1 Plotting Function

# %% [code] cell 39
def outlier_detection_and_plot_double_ts(
    df1,
    df2,
    col,
    outliers1,
    outliers2,
    mission_name1,
    mission_name2,
    year,
    out_path=out_path
):
    """Plot one common variable for two missions and highlight PCA outlier timestamps."""

    color1 = "steelblue"
    color2 = "darkorange"

    ts1 = df1[col].copy()
    ts2 = df2[col].copy()

    ts1.index = pd.to_datetime(ts1.index)
    ts2.index = pd.to_datetime(ts2.index)

    outlier_index1 = pd.to_datetime(outliers1.index).intersection(ts1.index)
    outlier_index2 = pd.to_datetime(outliers2.index).intersection(ts2.index)

    ts1_out = ts1.loc[outlier_index1]
    ts2_out = ts2.loc[outlier_index2]

    ts1_year = ts1[ts1.index.year == year]
    ts2_year = ts2[ts2.index.year == year]

    outlier_index1_year = outlier_index1.intersection(ts1_year.index)
    outlier_index2_year = outlier_index2.intersection(ts2_year.index)

    ts1_out_year = ts1_year.loc[outlier_index1_year]
    ts2_out_year = ts2_year.loc[outlier_index2_year]

    fig, axes = plt.subplots(
        2, 2,
        figsize=(18, 10),
        sharex=False
    )

    plot_data = [
        (axes[0, 0], ts1, ts1_out, color1, f"{mission_name1} - {col} full time series"),
        (axes[0, 1], ts2, ts2_out, color2, f"{mission_name2} - {col} full time series"),
        (axes[1, 0], ts1_year, ts1_out_year, color1, f"{mission_name1} - {col} zoom {year}"),
        (axes[1, 1], ts2_year, ts2_out_year, color2, f"{mission_name2} - {col} zoom {year}")
    ]

    for ax, ts, ts_out, color, title in plot_data:

        ax.plot(
            ts.index.to_numpy(),
            ts.to_numpy(),
            linewidth=0.8,
            color=color,
            label="Time series"
        )

        if not ts_out.empty:
            ax.scatter(
                ts_out.index.to_numpy(),
                ts_out.to_numpy(),
                color="red",
                s=30,
                label="Outliers",
                zorder=3
            )

        ax.set_title(title, fontsize=25)
        ax.set_xlabel("Time", fontsize=20)
        ax.set_ylabel("Value", fontsize=20)
        ax.tick_params(axis="both", labelsize=18)
        ax.grid(True, alpha=0.3)
        ax.legend()

    plt.tight_layout()

    plt.savefig(
        f"{out_path}{mission_name1}_{mission_name2}_outliers_{col}_pc{pca}_full_and_{year}.png"
    )

    plt.show()

# %% [markdown] cell 40
# ### 8.2 Select a Common Cluster Variable

# %% [code] cell 41
# Variables that are positively associated with the selected PC in both missions.
common = sorted(set(variable_pca_corr_m1.keys()) & set(variable_pca_corr_m2.keys()))
common

# %% [code] cell 42
col = common[0]

try:
    outlier_detection_and_plot_double_ts(
        df1=df_mission1,
        df2=df_mission2,
        col=col,
        outliers1=outliers_m1,
        outliers2=outliers_m2,
        mission_name1="Sentinel-3A",
        mission_name2="Sentinel-3B",
        year=2024
    )
except Exception as exc:
    print(f"No variables in this cluster, or selected variable not available: {exc}")

# %% [markdown] cell 43
# ## 9. Outliers on Text Calibration Curves
#
# Text calibration curves are aligned with PCA scores on common timestamps. The same outlier markers are then plotted on a selected calibration-curve variable.

# %% [markdown] cell 44
# ### 9.1 Alignment Function

# %% [code] cell 45
def aligning_text_and_scores(textcalcurves, scores):
    """Align text calibration curves with PCA score timestamps."""
    common_index = scores.index.intersection(textcalcurves.index)
    
    scores_aligned = scores.loc[common_index].sort_index()
    state_aligned  = textcalcurves.loc[common_index].sort_index()
    pca_with_state = scores_aligned.join(state_aligned, how="inner").dropna(axis=0, how="any")
    return pca_with_state

# %% [markdown] cell 46
# ### 9.2 Align Calibration Curves and Scores

# %% [code] cell 47
pca_with_state_m1 = aligning_text_and_scores(textcalcurves_m1, scores_m1)
pca_with_state_m2 = aligning_text_and_scores(textcalcurves_m2, scores_m2)

print('For Sentinel-3A, select a text cal-curve variable using the index between 0 and',len(pca_with_state_m1.iloc[:,10:].columns)-1)
print('For Sentinel-3B, select a text cal-curve variable using the index between 0 and',len(pca_with_state_m2.iloc[:,10:].columns)-1)

# %% [code] cell 48
# Text calibration curves available for both missions after alignment.
valid_textcalc = sorted(set(pca_with_state_m1.iloc[:, 10:].columns) & set(pca_with_state_m2.iloc[:, 10:].columns))
valid_textcalc

# %% [markdown] cell 49
# ### 9.3 Plot Selected Calibration Curve

# %% [code] cell 50
try:
    outlier_detection_and_plot_double_ts(
        df1=pca_with_state_m1,
        df2=pca_with_state_m2,
        col="CCB0102X_AVG",
        outliers1=outliers_m1,
        outliers2=outliers_m2,
        mission_name1="Sentinel-3A",
        mission_name2="Sentinel-3B",
        year=2024
    )
except Exception as exc:
    print(f"No available text cal-curve variables: {exc}")

# %% [markdown] cell 51
# ### 9.4 Stricter Rare-event Threshold
#
# If the initial threshold produces too many events for the calibration-curve view, this step recomputes the outliers with a stricter sigma threshold.

# %% [code] cell 52
# Stricter threshold used when the first threshold marks too many events.
outliers_m1 = outliers_sigma(scores_m1, f"PC{pca}", 8)
outliers_m2 = outliers_sigma(scores_m2, f"PC{pca}", 8)

# %% [code] cell 53
try:
    outlier_detection_and_plot_double_ts(
        df1=pca_with_state_m1,
        df2=pca_with_state_m2,
        col=valid_textcalc[19],
        outliers1=outliers_m1,
        outliers2=outliers_m2,
        mission_name1="Sentinel-3A",
        mission_name2="Sentinel-3B",
        year=2025
    )
except Exception as exc:
    print(f"No variables in this cluster, or selected cal-curve not available: {exc}")

# %% [markdown] cell 54
# ## 10. Frequency Analysis
#
# The FFT section compares dominant periods in either the selected PC score or a weighted combination of the first three PCs.

# %% [markdown] cell 55
# ### 10.1 Helper Functions

# %% [code] cell 56
def retrieve_ts(scores, explained, combo, detrend):
    """Select one PC score or a weighted PC combination and return its sampling interval."""
    if combo == True:
        # combination between the first 3 PCAs multiplied by their relative percentages
        ts = (scores["PC1"].dropna()*explained[0] + scores["PC2"].dropna()*explained[1] +  scores["PC3"].dropna()*explained[2]).copy()
    else:
        # Select the PCA component
        ts = scores[f"PC{pca}"].dropna()
    
    ts.index = pd.to_datetime(ts.index)
    ts = ts.sort_index()
    #dt = (ts.index[1] - ts.index[0]).total_seconds()
    
    if detrend == True:
        ts_det = scipy_detrend(ts)
        ts = pd.Series(ts_det, index=ts.index)
    dt = (ts.index[1] - ts.index[0]).total_seconds()
        
    return ts, dt

def plot_power_spectrum_double(
    ts1,
    ts2,
    dt1,
    dt2,
    mission_name1,
    mission_name2,
    combo,
    detrend,
    remove_annual=False,

    out_path=out_path
):
    """Compute and compare power spectra for two mission time series."""

    if detrend:
        d = "detrended"
    else:
        d = ""

    def compute_spectrum(ts, dt, remove_annual):

        signal = ts.values
        N = len(signal)

        if remove_annual:

            signal = signal - np.mean(signal)

            window = windows.hann(len(signal))
            signal = signal * window

            yf = rfft(signal)
            xf = rfftfreq(N, d=dt)

            ra = "removed_annual"

        else:

            yf = fft(signal - np.mean(signal))
            xf = fftfreq(N, dt)

            ra = ""

        power = np.abs(yf)**2

        # positive frequencies only
        mask = xf > 0

        freq = xf[mask]
        power = power[mask]

        # frequency -> period
        period_days = 1 / freq / 86400

        order = np.argsort(period_days)

        period_days = period_days[order]
        power = power[order]

        peaks, _ = find_peaks(
            power,
            prominence=np.max(power) * 0.05
        )

        if remove_annual:

            mask = (
                (period_days > 0.1) &
                (period_days < 100)
            )

            period_days = period_days[mask]
            power = power[mask]

            peaks, _ = find_peaks(
                power,
                prominence=np.max(power) * 0.05
            )

            n_peaks = 5

            idx = np.argsort(power[peaks])[-n_peaks:]

            peaks = peaks[idx]
        return period_days, power, peaks, ra

    # spectra
    period1, power1, peaks1, ra = compute_spectrum(
        ts1,
        dt1,
        remove_annual
    )

    period2, power2, peaks2, ra = compute_spectrum(
        ts2,
        dt2,
        remove_annual
    )

    # plotting
    fig, axes = plt.subplots(
        2,
        1,
        figsize=(10, 10),
        sharex=True
    )

    configs = [
        (
            axes[0],
            period1,
            power1,
            peaks1,
            "steelblue",
            mission_name1
        ),
        (
            axes[1],
            period2,
            power2,
            peaks2,
            "darkorange",
            mission_name2
        )
    ]

    for ax, period_days, power, peaks, color, mission in configs:

        ax.plot(
            period_days,
            power,
            linewidth=1,
            color=color
        )

        ax.scatter(
            period_days[peaks],
            power[peaks],
            color="red",
            zorder=3
        )
        
        plotted_labels = set()
        
        for p in peaks:
        
            period = period_days[p]
        
            if period < 1:
                label = f"{period * 24:.1f} h"
            else:
                label = f"{period:.1f} d"
        
            # Skip duplicate labels
            if label in plotted_labels:
                continue
        
            plotted_labels.add(label)
        
            ax.annotate(
                label,
                (period_days[p], power[p]),
                textcoords="offset points",
                xytext=(5, 5),
                fontsize=13
            )

        ax.set_xscale("log")
        ax.set_yscale("log")

        ax.set_ylabel("Power",fontsize=20)

        ax.grid(True, which="both", alpha=0.3)

    axes[1].set_xlabel("Period [days]",fontsize=20)
    plt.tick_params(axis="both", labelsize=16)
    plt.tight_layout()

    if combo:

        plt.savefig(
            f'{out_path}fft_{d}_{ra}_power_spectrum_combo_comparison.png'
        )

    else:

        plt.savefig(
            f'{out_path}fft_{d}_{ra}_power_spectrum_pca{pca}_comparison.png'
        )

    plt.show()

    return (
        power1,
        peaks1,
        period1,
        power2,
        peaks2,
        period2
    )

# %% [markdown] cell 57
# ### 10.2 Select Time Series

# %% [code] cell 58
combo = False
detrend = False

ts_m1, dt_m1 = retrieve_ts(scores_m1, explained_m1, combo, detrend)
ts_m2, dt_m2 = retrieve_ts(scores_m2, explained_m2, combo, detrend)

# %% [markdown] cell 59
# ### 10.3 Power Spectrum Comparison

# %% [code] cell 60
power_m1, peaks_m1, period_days_m1, power_m2, peaks_m2, period_days_m2 = plot_power_spectrum_double(
    ts_m1,
    ts_m2,
    dt_m1,
    dt_m2,
    "Sentinel-3A",
    "Sentinel-3B",
    combo,
    detrend
)

# %% [markdown] cell 61
# ### 10.4 Remove Annual and Semi-annual Cycles
#
# This helper removes annual and semi-annual harmonic components through a least-squares fit before recomputing the spectrum.

# %% [code] cell 62
def remove_annual_semiannual_cycles(ts):
    """
    Removes annual and semi-annual harmonic components from a time series.
    Assumes ts has a datetime index.
    """

    ts = ts.copy()
    ts.index = pd.to_datetime(ts.index)

    mask = ts.notna()
    y = ts.loc[mask].to_numpy()

    # Time in days from start
    t = (ts.loc[mask].index - ts.loc[mask].index[0]).total_seconds() / 86400

    annual_period = 365.25
    semiannual_period = 365.25 / 2

    X = np.column_stack([
        np.ones(len(t)),
        np.sin(2 * np.pi * t / annual_period),
        np.cos(2 * np.pi * t / annual_period),
        np.sin(2 * np.pi * t / semiannual_period),
        np.cos(2 * np.pi * t / semiannual_period),
    ])

    beta, _, _, _ = np.linalg.lstsq(X, y, rcond=None)

    fitted_cycle = X @ beta

    ts_removed = ts.copy()
    ts_removed.loc[mask] = y - fitted_cycle

    return ts_removed

# %% [code] cell 63
power_m1, peaks_m1, period_days_m1, power_m2, peaks_m2, period_days_m2 = plot_power_spectrum_double(
    ts_m1,
    ts_m2,
    dt_m1,
    dt_m2,
    "Sentinel-3A",
    "Sentinel-3B",
    combo,
    detrend,
    remove_annual=False
)

# %% [markdown] cell 64
# ## 11. STL Decomposition
#
# STL decomposes each selected signal into trend, daily seasonality, and residuals. The two missions are plotted in stacked panels for direct comparison.

# %% [markdown] cell 65
# ### 11.1 STL Function

# %% [code] cell 66
def plt_STL_double(
    ts1,
    ts2,
    combo,
    detrend,
    mission_name1="Sentinel-3A",
    mission_name2="Sentinel-3B",
    remove_annual=False,
    component="residuals",
    out_path=out_path
):
    """Run STL decomposition for two missions and plot one selected component."""

    if detrend:
        d = "detrended"
    else:
        d = ""

    if remove_annual:
        ts1 = remove_annual_semiannual_cycles(ts1)
        ts2 = remove_annual_semiannual_cycles(ts2)
        ra = "removed_annual_semiannual"
    else:
        ra = ""

    def compute_stl_component(ts, component):

        ts = ts.copy()
        ts.index = pd.to_datetime(ts.index)

        q01, q99 = ts.quantile([0.01, 0.99])
        ts_clean = ts.clip(lower=q01, upper=q99)

        period = 288   # 5 minutes -> 288 samples/day
        stl = STL(ts_clean, period=period, robust=True)
        res = stl.fit()

        component = component.lower()

        if component in ["trend", "low_frequency"]:
            y = res.trend
            label = "Trend / low-frequency component"

        elif component in ["seasonality", "seasonal", "daily_seasonality"]:
            y = res.seasonal
            label = "Daily seasonality"

        elif component in ["residuals", "residual", "resid"]:
            y = res.resid
            label = "Residuals"

        else:
            raise ValueError(
                "component must be one of: 'trend', 'seasonality', or 'residuals'"
            )

        return y, label, res

    def get_outlier_values(y, outliers):

        if outliers is None:
            return None

        outlier_index = pd.to_datetime(outliers.index)
        outlier_index = outlier_index.intersection(y.index)

        if len(outlier_index) == 0:
            return None

        return y.loc[outlier_index]

    y1, component_label, res1 = compute_stl_component(ts1, component)
    y2, _, res2 = compute_stl_component(ts2, component)

    y1_out = get_outlier_values(y1, outliers_m1)
    y2_out = get_outlier_values(y2, outliers_m2)

    fig, axes = plt.subplots(
        2, 1,
        figsize=(14, 8),
        sharex=True,
        gridspec_kw={"hspace": 0.2}
    )

    axes[0].plot(
        y1.index.to_numpy(),
        y1.to_numpy(),
        linewidth=1,
        color="steelblue",
        label=component_label
    )

    axes[0].set_title(f"{mission_name1}", fontsize=22)
    axes[0].set_ylabel("Value",fontsize=20)
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    axes[1].plot(
        y2.index.to_numpy(),
        y2.to_numpy(),
        linewidth=1,
        color="darkorange",
        label=component_label
    )

    axes[1].set_title(f"{mission_name2}", fontsize=22)
    axes[1].set_ylabel("Value",fontsize=20)
    axes[1].set_xlabel("Time",fontsize=20)
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()

    if combo:
        filename = (
            f"{out_path}fft_{d}_{ra}_STL_combo_"
            f"{component}_{mission_name1}_{mission_name2}.png"
        )
    else:
        filename = (
            f"{out_path}fft_{d}_{ra}_STL_pca{pca}_"
            f"{component}_{mission_name1}_{mission_name2}.png"
        )
    plt.xticks(size=18)
    plt.yticks(size=18)
    plt.tight_layout()
    plt.savefig(filename)
    plt.show()

    return res1, res2

# %% [markdown] cell 67
# ### 11.2 Plot Decomposition Components

# %% [code] cell 68
plt_STL_double(
    ts1=ts_m1,
    ts2=ts_m2,
    combo=combo,
    detrend=detrend,
    component="residuals",
)

# %% [code] cell 69
plt_STL_double(
    ts1=ts_m1,
    ts2=ts_m2,
    combo=combo,
    detrend=detrend,
    component="trend",
)

# %% [code] cell 70
plt_STL_double(
    ts1=ts_m1,
    ts2=ts_m2,
    combo=combo,
    detrend=detrend,
    component="seasonality",
)
